### ISSUE TITLE
General design

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/seath#2]
Figure out the general design of Seath: what on-chain and off-chain functionality are required, how users' protocols will integrate with Seath, what tech stack we are going to use, protocol to use for demo and testing.

Ongoing discussion currently going [here](https://www.notion.so/Design-considerations-15db24fb077147558498ec761db58383) and [here](https://www.notion.so/Demo-protocol-design-f1e41bcdb2ac4957b7209485a2700ecf)

**Comment by Luis-omega** [comment]
for testing we would like to have [plutip](https://github.com/mlabs-haskell/plutip) since our main focus is the interaction with the blockchain
