### ISSUE TITLE
Stage 1 

### ISSUE THREAD

**Issue by Luis-omega** [mlabs-haskell/seath#22]
With the closing of #11  on develop, when we merge #21 we would be ready to make the demo for the first stage. 

Is there something else that we should do about it or before it? 

Maybe we need to improve the logs for the demo? 

I think that having #20  would be nice, but it can wait or be done in parallel with the second stage. 

Additional tasks for stage one:
- [ ] #29 
- [ ] Update 1st part of the demo

**Comment by mikekeke** [comment]
Regarding [this proposal](https://github.com/mlabs-haskell/seath/pull/21#discussion_r1139755759):
> For the demo, shall we use something like this but with much short output?

I agree that we should make some clear log reporting for the demo (and for ourselves too, probably). Some log with clear representation of chain of transaction built by Seath. Maybe just TX ID's, like
```
ID-1
-> ID-2
-> ID-3
...
```
?
So we can show them in cardanoscan afterwards.

Also, maybe some simple representation of state before chain was submitted and after.

I think that people, who will watch the demo during acceptance, won't be too technical (if technical at all), so it's better to make things as clear as possible.

**Comment by mikekeke** [comment]
I was also thinking about some "script generator", so we can generate fresh script easily for the demo if we need. But we can also just change source before exporting. Add some line like `traceIfFalse "Script-{UUID} True`.

**Comment by Luis-omega** [comment]
At first I thouth that we can use the `dot` language and a renderer like `https://github.com/csicar/purescript-graphviz` to do a graphical display of what's happening in the same terms as `plutus-pioneer` diagrams. 

Now I think that, as we already using `Purscript` we can serve a little webpage that can be used as front end, like in the future (next stage demo) we can set the actions there and watch. But right now the only config available would be the number of users (from 1 to 4). So, we would have a webpage with a single form for the number of wallets, a submission button, and a table with the actions, the state of the signature of them, and the final transaction hash with a link to cardanoScan.

**Comment by Luis-omega** [comment]
I tried 

`spago bundle-app --main test/Main.purs --to output.js -v`

Then the code compile but then I got this message: 

```
[debug] Running command: `purs bundle "output/*/*.js" -m test/Main.purs --main test/Main.purs -o output.js`
Couldn't find a CommonJS module for the specified main module: test/Main.purs
[error] Bundle failed.
```

It seems to be the error  of 

`purs bundle "output/*/*.js" -m test/Main.purs --main test/Main.purs -o output.js`

But I don't know what I'm doing wrong.
