### ISSUE TITLE
Scaffold repository

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/seath#3]
Scaffold repository.
Current requirements are:
- CTL for off-chain
- PlutusTx and Haskell for on-chain

Acceptance criteria: 
- [ ] simple contract to pay from PKH to validator script can be executed

**Comment by Luis-omega** [comment]
Since you already begin with the on-chain part, I would begin to work in the off-chain, please open a pull request for https://github.com/mlabs-haskell/seath/tree/on-chain-setup/on-chain, and I would open one for off-chain and link it to this issue.

**Comment by Luis-omega** [comment]
Solved by #9
