### ISSUE TITLE
Add linting and formatting checks to CI

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/seath#7]

**Comment by Luis-omega** [comment]
I took a look at it but in the end, I just add `easy-ps.purs-tidy` to the dev shell for `on-chain`, this way I have autoformatting in purescritp code in neovim.

**Comment by Luis-omega** [comment]
Update: I added files for `off-chain` formating, now `make format` in the `off-chain` folder, works.

**Comment by Luis-omega** [comment]
Update: in the last commit for develop (8f27beb598c55f3463eddd76217af3352cbfe226)  we now have a `check-format` in the `off-chain/Makefile`.

**Comment by mikekeke** [comment]
`make check-format` added to CI checks in eb3844f
